name: flutter_bluetooth_serial_example
version: 0.2.2
description: Demonstrates how to use the `flutter_bluetooth_serial` plugin.
authors: 
- Patryk Ludwikowski <patryk.ludwikowski.7@gmail.com>
homepage: https://github.com/edufolly/flutter_bluetooth_serial/tree/master/example/

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^1.0.1

  cupertino_icons: ^0.1.2
  flare_flutter: any
  speech_recognition: "^0.3.0"
  toast: any
  permission: any
  permission_handler: ^3.0.0  
  rxdart: any 
  provider: any
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_serial:
    path: ../
  # speech_recognition:
  #   path: ../../speech_recognition_master/
flutter:
  uses-material-design: true

  assets: 
    # - assets/listen.flr
    - assets/listen(4).flr
    - assets/robot.flr
    - assets/forward.flr
    - assets/backward.flr
    - assets/right.flr
    - assets/left.flr
    - assets/robotSad.flr
